name: Tests for sha256-avx2 implementation

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        size:
          - 128
          - 192
          - 256
        option:
          - s
          - f
        thash:
          - simple
          - robust
    steps:
      - uses: actions/checkout@v1
      - name: Run make
        run: |
          make -C sha256-avx2 THASH=${{ matrix.thash }} clean
          make -C sha256-avx2 THASH=${{ matrix.thash }} PARAMS=sphincs-sha256-${{ matrix.size }}${{ matrix.option }} tests
          make -C sha256-avx2 THASH=${{ matrix.thash }} PARAMS=sphincs-sha256-${{ matrix.size }}${{ matrix.option }} test
          make -C sha256-avx2 THASH=${{ matrix.thash }} PARAMS=sphincs-sha256-${{ matrix.size }}${{ matrix.option }} PQCgenKAT_sign
      - name: Run PQCgenKAT_sign
        run: python3 vectors.py sphincs-sha256-${{ matrix.size }}${{ matrix.option }}-${{ matrix.thash }} sha256-avx2

#  vim: set ft=yaml ts=2 sw=2 et :
